services:
  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - "6380:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: infra_ops
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: